export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen bg-purple-50 px-6 py-12 text-left">
            <div className="max-w-4xl mx-auto bg-white shadow-md rounded-xl p-8">

                <h1 className="text-4xl font-bold text-purple-900 mb-8 text-center">
                    Privacy Policy
                </h1>

                <section className="mb-6">
                    <p className="text-purple-800 leading-relaxed">
                        Welcome to Curalia App. Curalia is an AI-powered health
                        assistant that helps users receive health-related guidance
                        through conversations with artificial intelligence.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        1. Information We Collect
                    </h2>

                    <p className="text-purple-800 leading-relaxed">
                        Curalia may store conversation history and user-provided
                        health-related information locally on the device to support
                        app functionality.
                    </p>

                    <p className="text-purple-800 leading-relaxed mt-3">
                        The app does not require account registration and does not
                        intentionally collect personal information such as your
                        name, address, or phone number.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        2. App Features
                    </h2>

                    <ul className="list-disc list-inside text-purple-800 space-y-1">
                        <li>AI-powered health conversations</li>
                        <li>Symptom and health-related discussions</li>
                        <li>Conversation history storage</li>
                        <li>Conversation history deletion</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        3. Internet Connection
                    </h2>

                    <p className="text-purple-800 leading-relaxed">
                        Curalia requires an internet connection to communicate
                        with AI services and generate responses.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        4. AI Services
                    </h2>

                    <p className="text-purple-800 leading-relaxed">
                        Curalia uses artificial intelligence services to generate
                        responses based on user input. Responses are generated
                        automatically and should not be considered professional
                        medical advice.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        5. Conversation Storage
                    </h2>

                    <p className="text-purple-800 leading-relaxed">
                        Conversation history may be stored locally on your device
                        to improve user experience and allow access to previous
                        discussions.
                    </p>

                    <p className="text-purple-800 leading-relaxed mt-3">
                        Users can delete stored conversations at any time using
                        the clear history feature.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        6. Medical Disclaimer
                    </h2>

                    <p className="text-purple-800 leading-relaxed">
                        Curalia is an AI-powered informational tool and is not a medical
                        device, healthcare provider, or diagnostic service.
                    </p>

                    <p className="text-purple-800 leading-relaxed mt-3">
                        Responses generated by the application are produced automatically
                        by artificial intelligence and may not always be accurate,
                        complete, or suitable for your specific situation.
                    </p>

                    <p className="text-purple-800 leading-relaxed mt-3">
                        The information provided by Curalia is for informational purposes
                        only and is not intended to replace professional medical advice,
                        diagnosis, or treatment.
                    </p>

                    <p className="text-purple-800 leading-relaxed mt-3">
                        Users should always consult a qualified physician or healthcare
                        professional before making medical decisions or acting upon any
                        information provided by the application.
                    </p>

                    <p className="text-purple-800 leading-relaxed mt-3">
                        In case of a medical emergency, contact emergency services or a
                        licensed healthcare provider immediately.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        7. Changes to This Policy
                    </h2>

                    <p className="text-purple-800 leading-relaxed">
                        We may update this Privacy Policy from time to time.
                        Any changes will be posted on this page.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-semibold text-purple-900 mb-3">
                        8. Contact Us
                    </h2>

                    <p className="text-purple-800 leading-relaxed">
                        If you have any questions regarding this Privacy Policy,
                        please contact us at:
                        <a
                            href="mailto:anhongoc1306@gmail.com"
                            className="text-purple-600 underline ml-1"
                        >
                            anhongoc1306@gmail.com
                        </a>
                    </p>
                </section>

            </div>
        </div>
    );
}